# -*- coding: utf-8 -*-
"""Health analysis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YWSs21HgOfgC8AD96BD8OelHw1vaSQTa
"""

import pandas as pd
df=pd.read_csv("/patients.csv")

print("Data Loaded!" "Here's a preview:")
print (df.head(11))

total_patients=len(df)
print(f"Q1->Total Patients:{total_patients}")

avg_age=round(df["age"].mean(),1)
print(f"Q2->Average Age:{avg_age} years")

diabetes_df=df[df["condition"]=="Diabetes"]
diabetes_patients=len(diabetes_df)
print(f"Q3->Diabetes Patients:{diabetes_patients}")

summary= pd.DataFrame({
  'metric':["Total Patients", "Average Age (yrs)","Diabetes Count"],
    'value':[total_patients,avg_age,len(diabetes_df)]
})
summary.to_csv("summary_report.csv",index=False)
print("Summary saved to summary_report.csv")
print(summary)